name = "scf"
version = "0.1.0"
license = "license"
author = "albert"
maintainer = "92109627+Albkat@users.noreply.github.com"
copyright = "Copyright 2023, albert"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
